### ISSUE TITLE
the gui opens up weird and is completely off screen and way to large

### ISSUE THREAD

**Issue by syskey4603** [CorruptionHades/VapeMenu#1]
![Screenshot 2023-06-08 215652](https://github.com/CorruptionHades/VapeMenu/assets/83065600/16d61002-ee29-4aba-b1e5-4c735d3f4edb)

appreciate if you can help im not really experienced with this and am just trying it out
when u move the entire gui small parts of the categories show up and others get hidden and the actual config options and module names are completely hidden and the category display takes up 1% of the black box

**Comment by CorruptionHades** [comment]
set gui scale to 2

**Comment by CorruptionHades** [comment]
Fixed this
